// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nzrepjskraxvoczvoehf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cmVwanNrcmF4dm9jenZvZWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjIzMjksImV4cCI6MjA3Mjc5ODMyOX0.GIDVZEIiYHVtdW_zqk26fxK7MfnSFoPw4gPstv2S6lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});


